target("llaisys-device-nvidia")
    set_kind("static")
    add_deps("llaisys-utils")
    set_languages("cxx17")
    set_values("cuda.rdc", false)
    add_files("../src/device/nvidia/*.cu")
    add_cugencodes("native")
    add_cuflags("-Xcompiler=-fPIC")
    add_links("cudart")
    on_install(function (target) end)
target_end()

target("llaisys-ops-nvidia")
    set_kind("static")
    add_deps("llaisys-tensor")
    set_languages("cxx17")
    set_values("cuda.rdc", false)
    add_files("../src/ops/*/nvidia/*.cu")
    add_cugencodes("native")
    add_cuflags("-Xcompiler=-fPIC")
    add_links("cudart", "cublas")
    on_install(function (target) end)
target_end()
